name: New feature
description: Suggest or request a new feature
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Please fill out the sections below to properly describe the new feature you are suggesting.
    - type: dropdown
    id: Owner
    attributes:
      label: "Who is the owner of this feature"
      options:
        - "Connor Smith"
        - "Peter Sherman"
        - "Garrett Heathcote"
        - "David Coons"
        - "Lindsay Burdick"
  - type: text 
    id: context
    attributes:
      label: Reporter/Department
  - type: textarea
    id: description
    attributes:
      label: Description:
      placeholder: As a <user>, I want <goal> so that <reason>
    validations:
      required: true
  - type: textarea
    id: rationale
    attributes:
      label: Business/Use Case Impact
      placeholder: It will allow the company to do Y that is needed for Z.
  - type: textarea
    id: context
    attributes:
      label: Acceptance Criteria
      placeholder: |
        What is the required acceptance criteria?
  - type: textarea
    id: context
    attributes:
      label: Expected Outcome
      placeholder: |
        What is the expected outcome?
  - type: textarea
    id: attachments
    attributes:
      label: Attachments (optional)
